# Book settings
title: "Mellor Group Handbook"
author: 
logo: contents/img/Brain_logo.png
url: "http://mellor-lab.github.io/mellor_lab_handbook"


html:
    google_analytics_id: G-DFGRNXM71K
    home_page_in_navbar       : false
    logo_only                 : true
    extra_navbar: |
        <div>
            Handbook created using <a href="https://github.com/very-good-science/our-meta-handbook">Our Handbook</a>.
            Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>.
        </div>


sphinx:
    extra_extensions:
        - sphinx_inline_tabs
        - sphinx_design
    extra_footer: |
        <p>
            License: <a href="https://creativecommons.org/licenses/by/3.0/legalcode">CC-BY 3.0</a>
        </p>
    config:
        html_show_copyright: false
        html_theme_options:    
            use_download_button: false

# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
    - html_image
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context
